name: Build ARMv7 + OTA bundle (Cortex-A7)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf

      - name: Configure Cargo
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << 'EOF'
          [source.crates-io]
          replace-with = 'ustc'
          [source.ustc]
          registry = "https://mirrors.ustc.edu.cn/crates.io-index"
          [target.armv7-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          EOF

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf rauc openssl tar
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        env:
          RUSTFLAGS: -C target-feature=+neon
        run: cross build --target armv7-unknown-linux-gnueabihf --release

      - name: Prepare OTA files
        run: |
          set -e
          mkdir -p ota/output ota/keys
          STAGE="$(mktemp -d)"
          mkdir -p "$STAGE/opt/scan-demo" "$STAGE/usr/local/bin"
          
          cp target/armv7-unknown-linux-gnueabihf/release/scan_demo "$STAGE/opt/scan-demo/"
          cp -r ui "$STAGE/opt/scan-demo/"
          cp -r scripts "$STAGE/opt/scan-demo/"
          
          cat > "$STAGE/usr/local/bin/start-scan-demo.sh" << 'EOS'
          #!/bin/sh
          cd /opt/scan-demo
          export DISPLAY=:0
          ./scan_demo &
          EOS
          chmod +x "$STAGE/usr/local/bin/start-scan-demo.sh"
          
          tar -czf ota/output/app-update.tar.gz -C "$STAGE" .

      - name: Generate keys
        run: |
          mkdir -p ota/keys
          if [ ! -f ota/keys/rauc.key ]; then
            openssl genrsa -out ota/keys/rauc.key 2048
            openssl req -new -x509 -key ota/keys/rauc.key -out ota/keys/rauc.cert -days 365 \
              -subj "/CN=STM32MP-OTA-Cert"
          fi

      - name: Create RAUC bundle
        run: |
          set -e
          echo "创建RAUC bundle..."
          
          # 方法1: 解压方式（推荐）
          BUNDLE_DIR="$(mktemp -d)"
          tar -xzf ota/output/app-update.tar.gz -C "$BUNDLE_DIR"
          
          rauc bundle \
            --cert=ota/keys/rauc.cert \
            --key=ota/keys/rauc.key \
            "$BUNDLE_DIR" \
            "ota/output/update-${{ github.sha }}.raucb"
          
          echo "✓ 打包成功"
          ls -la "ota/output/update-${{ github.sha }}.raucb"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scan-demo-ota-armv7
          path: |
            target/armv7-unknown-linux-gnueabihf/release/scan_demo
            ui/**
            scripts/**
            ota/output/update-${{ github.sha }}.raucb
            ota/keys/rauc.cert
