name: Build ARMv7 + OTA bundle (Cortex-A7)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf

      - name: Configure Cargo
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << 'EOF'
          [source.crates-io]
          replace-with = 'ustc'
          [source.ustc]
          registry = "https://mirrors.ustc.edu.cn/crates.io-index"
          [target.armv7-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          EOF

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf rauc openssl tar tree

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        env:
          RUSTFLAGS: -C target-feature=+neon
        run: cross build --target armv7-unknown-linux-gnueabihf --release

      - name: Generate RAUC keys
        run: |
          mkdir -p ota/keys
          if [ ! -f ota/keys/rauc.key ]; then
            openssl genrsa -out ota/keys/rauc.key 2048
            openssl req -new -x509 -key ota/keys/rauc.key -out ota/keys/rauc.cert -days 365 \
              -subj "/CN=STM32MP-OTA-Cert"
          fi
          echo "RAUC证书信息:"
          openssl x509 -in ota/keys/rauc.cert -noout -subject -dates

      - name: Create RAUC bundle
        run: |
          set -e
          echo "=== 创建RAUC bundle ==="
          
          # 确保输出目录存在
          mkdir -p ota/output
          
          # 创建临时bundle目录
          BUNDLE_DIR="$(mktemp -d)"
          echo "Bundle目录: $BUNDLE_DIR"
          
          # 创建目录结构
          mkdir -p "$BUNDLE_DIR/bin"
          mkdir -p "$BUNDLE_DIR/ui"
          mkdir -p "$BUNDLE_DIR/scripts"
          
          # 复制应用文件
          echo "复制应用文件..."
          cp target/armv7-unknown-linux-gnueabihf/release/scan_demo "$BUNDLE_DIR/bin/"
          [ -d "ui" ] && cp -r ui/* "$BUNDLE_DIR/ui/" 2>/dev/null || echo "UI目录为空"
          [ -d "scripts" ] && cp -r scripts/* "$BUNDLE_DIR/scripts/" 2>/dev/null || echo "Scripts目录为空"
          
          # 创建manifest文件
          echo "创建manifest..."
          cat > "$BUNDLE_DIR/manifest.raucm" << 'EOF'
          [update]
          compatible=STM32MP1,ScanDemo
          version=${{ github.sha }}
          description=Scan Demo Application Update
          bundle.format=plain
          
          [image.app]
          filename=bin/scan_demo
          archive=none
          
          [image.ui]
          filename=ui/main.qml
          archive=none
          
          [image.scripts]
          filename=scripts/run_device.sh
          archive=none
          EOF
          
          # 只保留实际存在的文件到manifest中
          cat > "$BUNDLE_DIR/manifest.raucm" << 'EOF'
          [update]
          compatible=STM32MP1,ScanDemo
          version=${{ github.sha }}
          description=Scan Demo Application Update
          bundle.format=plain
          
          [image.app]
          filename=bin/scan_demo
          archive=none
          EOF
          
          echo "Manifest内容:"
          cat "$BUNDLE_DIR/manifest.raucm"
          
          echo "Bundle目录结构:"
          tree "$BUNDLE_DIR" || find "$BUNDLE_DIR" -type f | sort
          
          # 检查文件权限
          ls -la "$BUNDLE_DIR/bin/"
          
          # 创建RAUC bundle
          echo "开始打包..."
          OUTPUT_FILE="ota/output/update-${{ github.sha }}.raucb"
          
          rauc bundle \
            --cert=ota/keys/rauc.cert \
            --key=ota/keys/rauc.key \
            "$BUNDLE_DIR" \
            "$OUTPUT_FILE" || {
              echo "RAUC打包失败!"
              echo "检查文件:"
              ls -la ota/keys/
              ls -la ota/output/
              echo "Bundle目录内容:$(mktemp -d)"
              tree "$BUNDLE_DIR" || find "$BUNDLE_DIR" -type f
              exit 1
            }
          
          echo "✓ RAUC bundle创建成功!"
          ls -la "$OUTPUT_FILE"
          
          # 清理临时目录
          rm -rf "$BUNDLE_DIR"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scan-demo-ota-armv7
          path: |
            target/armv7-unknown-linux-gnueabihf/release/scan_demo
            ui/**
            scripts/**
            ota/output/update-${{ github.sha }}.raucb
            ota/keys/rauc.cert
