name: Build RAUC for ARM and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-rauc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install RAUC and create deployment package
        run: |
          # 安装 RAUC
          sudo apt-get update
          sudo apt-get install -y rauc
          
          # 创建部署目录结构
          mkdir -p rauc-deploy/usr/local/bin
          mkdir -p rauc-deploy/etc/rauc
          
          # 复制 RAUC 二进制文件
          cp /usr/bin/rauc rauc-deploy/usr/local/bin/
          
          # 创建系统配置文件
          cat > rauc-deploy/etc/rauc/system.conf << 'EOF'
          [system]
          compatible=STM32MP1,ScanDemo
          bootloader=u-boot
          
          [slot.rootfs.0]
          device=/dev/mmcblk0p2
          type=ext4
          bootname=A
          
          [slot.rootfs.1]
          device=/dev/mmcblk0p3
          type=ext4
          bootname=B
          EOF
          
          # 生成密钥和证书
          openssl genrsa -out rauc-deploy/etc/rauc/rauc.key 2048
          openssl req -new -x509 -key rauc-deploy/etc/rauc/rauc.key \
            -out rauc-deploy/etc/rauc/rauc.cert -days 365 \
            -subj "/CN=STM32MP-OTA-Cert"
          
          # 创建安装脚本
          cat > rauc-deploy/install.sh << 'EOF'
          #!/bin/bash
          echo "=== 安装 RAUC ==="
          
          # 复制二进制文件
          cp usr/local/bin/rauc /usr/local/bin/
          chmod +x /usr/local/bin/rauc
          
          # 创建配置目录
          mkdir -p /etc/rauc
          
          # 复制配置文件
          cp etc/rauc/* /etc/rauc/
          chmod 644 /etc/rauc/rauc.cert
          chmod 600 /etc/rauc/rauc.key
          chmod 644 /etc/rauc/system.conf
          
          # 验证安装
          echo "验证安装..."
          /usr/local/bin/rauc --version
          /usr/local/bin/rauc status
          
          echo "✓ RAUC 安装完成"
          EOF
          
          chmod +x rauc-deploy/install.sh
          
          # 打包
          tar -czf rauc-deploy.tar.gz rauc-deploy/
          
          # 显示包内容
          echo "部署包内容:"
          tar -tzf rauc-deploy.tar.gz | head -20

      - name: Upload RAUC deployment package
        uses: actions/upload-artifact@v4
        with:
          name: rauc-deploy-arm
          path: |
            rauc-deploy.tar.gz
            rauc-deploy/
          retention-days: 30
